### ISSUE TITLE
Showing error when try to open lemon

### ISSUE THREAD

**Issue by karim1556** [Hax4us/TermuxBlack#22]
events.js:291       throw er; // Unhandled 'error' event       ^  Error: listen EADDRINUSE: address already in use :::22222     at Server.setupListenHandle [as _listen2] (net.js:1316:16)     at listenInCluster (net.js:1364:12)     at Server.listen (net.js:1450:7)     at Server.listen.Server.attach (/data/data/com.termux/files/usr/share/lemon/server/node_modules/socket.io/lib/index.js:273:9)     at new Server (/data/data/com.termux/files/usr/share/lemon/server/node_modules/socket.io/lib/index.js:59:17)     at Function.Server [as listen] (/data/data/com.termux/files/usr/share/lemon/server/node_modules/socket.io/lib/index.js:44:41)     at Object.<anonymous> (/data/data/com.termux/files/usr/share/lemon/server/index.js:27:20)     at Module._compile (internal/modules/cjs/loader.js:1251:30)     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1272:10)     at Module.load (internal/modules/cjs/loader.js:1100:32) Emitted 'error' event on Server instance at:     at emitErrorNT (net.js:1343:8)     at processTicksAndRejections (internal/process/task_queues.js:80:21) {   code: 'EADDRINUSE',   errno: -98,   syscall: 'listen',   address: '::',   port: 22222

**Comment by murtu90** [comment]
![Uploading Screenshot_2023-05-27-13-28-16-066_com.termux.jpg…]()
Any solution for this eror
